using System.ComponentModel.DataAnnotations.Schema;
using System.Data;

namespace DataAOT;

/// <summary>
/// This is information about each database field identified from
/// the data model properties.  It can be accessed within a DbGateway
/// via its Fields property
/// </summary>
public struct DbField
{
    /// <summary>
    /// The name of the property
    /// </summary>
    public string PropertyName { get; set; }
    
    /// <summary>
    /// The property's type
    /// </summary>
    public Type PropertyType { get; set; }

    /// <summary>
    /// The database field name corresponding to the property
    /// </summary>
    public string FieldName { get; set; }
    
    /// <summary>
    /// The database field's type
    /// </summary>
    public DbType FieldType { get; set; }

    /// <summary>
    /// If true, this property and field are designated nullable
    /// </summary>
    public bool IsNullable { get; set; }
    /// <summary>
    /// If true, this property's field is a primary key
    /// </summary>
    public bool IsKey { get; set; }

    /// <summary>
    /// Specifies whether the field's value is generated by the database (identity or computed)
    /// </summary>
    public DatabaseGeneratedOption DatabaseGenerated { get; set; }
}